modLoader="javafml"
loaderVersion="[37,)"
license="MIT License"

[[mods]]
modId="craftablechainmail"
version="1.0"
displayName="Craftable Chainmail Reborn"
credits="Hashtag233"
displayURL="https://www.curseforge.com/minecraft/mc-mods/craftable-chainmail-reborn"
updateJSONURL="https://gitee.com/hashtag233/craftable-chainmail-reborn/raw/master/update.json"
logoFile="logo.png"
authors="Hashtag233, MCreator"
description='''
Adds a crafting recipe for chainmail armor.
'''

[[dependencies.craftablechainmail]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1]"
    ordering="NONE"
    side="BOTH"




